### ISSUE TITLE
I have no idea what I'm doing

### ISSUE THREAD

**Issue by AtesIsf** [Danyy427/TaraOS#1]
💀

**Comment by ghost** [comment]
@AtesIsf  [Os](https://wiki.osdev.org/Expanded_Main_Page)

**Comment by AtesIsf** [comment]
👍

**Comment by ghost** [comment]
@AtesIsf 

```
findlenloop:
    inc cx
    cmp [si+cx], 0x0
    je printhexloop
    jmp findlenloop
```

Length bulmana gerek yok `si` zaten 16 bit. Bi de CS derslerinde yaptığımız gibi digit digit alman lazım 0x30'la toplamadan önce

**Comment by ghost** [comment]
@AtesIsf Bi de bi şeyi pushlamadan önce pull request açalım, direk mergleme, ben de öyle yaparım herkes kodu kontrol etsin. Eğer pull request atmadan mergliceksen önce test etmen gereksin.

**Comment by AtesIsf** [comment]
ok
